version: '3.8'

volumes:
  postgresql_data:
    driver: local


services:
  postgresql:
    image: postgres:13.3
    volumes:
      - postgresql_data:/var/lib/postgres
    environment:
      POSTGRES_DB: librettino
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 7432:5432